version: '3'
services:
  four-characters-test-db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: fc_test
      POSTGRES_PASSWORD: fc_test
      TZ: 'Asia/Tokyo'
    volumes:
      - fc-test-db-volume:/var/lib/postgresql/data
volumes:
  fc-test-db-volume:
